package com.royalcyber.monitorms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-09T22:57:43.148+10:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "MonitorMSSOAP_HTTP_Service", 
                  wsdlLocation = "file:/C:/Users/dvaddi/Workspace_DLUIMerge/DLJWebService/WebContent/WEB-INF/wsdl/MonitorMSSOAP_HTTP_Port.wsdl",
                  targetNamespace = "http://royalcyber.com/MonitorMS") 
public class MonitorMSSOAPHTTPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://royalcyber.com/MonitorMS", "MonitorMSSOAP_HTTP_Service");
    public final static QName MonitorMSSOAPHTTPPort = new QName("http://royalcyber.com/MonitorMS", "MonitorMSSOAP_HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/dvaddi/Workspace_DLUIMerge/DLJWebService/WebContent/WEB-INF/wsdl/MonitorMSSOAP_HTTP_Port.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MonitorMSSOAPHTTPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/dvaddi/Workspace_DLUIMerge/DLJWebService/WebContent/WEB-INF/wsdl/MonitorMSSOAP_HTTP_Port.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MonitorMSSOAPHTTPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MonitorMSSOAPHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MonitorMSSOAPHTTPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MonitorMSSOAPHTTPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MonitorMSSOAPHTTPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MonitorMSSOAPHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns MonitorMSPortType
     */
    @WebEndpoint(name = "MonitorMSSOAP_HTTP_Port")
    public MonitorMSPortType getMonitorMSSOAPHTTPPort() {
        return super.getPort(MonitorMSSOAPHTTPPort, MonitorMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MonitorMSPortType
     */
    @WebEndpoint(name = "MonitorMSSOAP_HTTP_Port")
    public MonitorMSPortType getMonitorMSSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(MonitorMSSOAPHTTPPort, MonitorMSPortType.class, features);
    }

}
